spring:
  application:
    name=paymentManagementSystem
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: P@&&w0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081
